---
apiVersion: v1
kind: Namespace
metadata:
  name: shinobi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shinobi
  namespace: shinobi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinobi
  template:
    metadata:
      labels:
        app: shinobi
    spec:
      containers:
      - name: shinobi
        image: ghcr.io/thehonker/shinobi-k8s:dev-latest
        command:
          - pm2-docker
        args:
          - /home/Shinobi/Docker/pm2.yml
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: shmem
          mountPath: /dev/shm/streams
        - name: shinobi-videos
          mountPath: /videos
        - name: conf-json
          mountPath: /home/Shinobi/conf.json
          subPath: conf.json
        - name: super-json
          mountPath: /home/Shinobi/super.json
          subPath: super.json
      volumes:
      - name: shmem
        emptyDir:
          medium: Memory
      - name: shinobi-videos
        persistentVolumeClaim:
          claimName: shinobi-videos
      - name: conf-json
        secret:
          secretName: conf-json
      - name: super-json
        secret:
          secretName: super-json

---
apiVersion: v1
kind: Service
metadata:
  name: shinobi
  namespace: shinobi
spec:
  selector:
    app: shinobi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shinobi-videos
  namespace: shinobi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-storage-class
  resources:
    requests:
      storage: ALL_OF_IT
